package com.github.vlsidlyarevich.JSFSpringAnnotations.JSFSpringSecurity.security.configuration;


import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class ApplicationSecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
